### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by MariiaKravchuk** [MariiaKravchuk/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by MariiaCollaborator** [comment]
Homer Jay Simpson is the spouse of Marge Simpson and father of Bart Simpson, Lisa Simpson, and Maggie Simpson. Although Homer has many flaws, he has shown to have great caring, love, and even bravery to those he cares about and, sometimes, even others he doesn't. Homer may just be a normal man, but he has had many great achievements and experiences in his life. He has won a Grammy, an Academy Award, a Pulitzer Prize, been to space, and has saved Springfield many times.
