### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by MariiaKravchuk** [MariiaKravchuk/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by MariiaCollaborator** [comment]
🏡 742 Evergreen Terrace
📞 555-0113
📖 https://en.wikipedia.org/wiki/Homer_Simpson
📸 https://www.instagram.com/thesimpsons/
